package com.example.data

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import com.example.model.TradeAction
import com.example.model.TradeSetup
import java.util.UUID

/**
 * Room entity representing trade signals generated by AI or technical analysis engines,
 * persisted locally for offline review, auditing, and execution.
 */
@Entity(
    tableName = "trade_signals",
    indices = [
        Index(value = ["pairSymbol", "timestamp"]),
        Index(value = ["signalId"], unique = true),
        Index(value = ["status"]),
        Index(value = ["action"]),
        Index(value = ["timestamp"])
    ]
)
data class TradeSignalEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val signalId: String = UUID.randomUUID().toString(),
    val pairSymbol: String,
    val timeframe: String,
    val action: String, // "BUY", "SELL", "WAIT"
    val isValid: Boolean = true,
    val entryPrice: Double,
    val stopLoss: Double,
    val takeProfit1: Double,
    val takeProfit2: Double,
    val riskRewardRatio: Double,
    val confidenceScore: Double = 0.85, // 0.0 - 1.0 (e.g. 85%)
    val signalType: String = "AI_CONFLUENCE", // "AI_CONFLUENCE", "EMA_CROSS", "SUPPLY_DEMAND", "BREAKOUT"
    val status: String = "ACTIVE", // "ACTIVE", "TRIGGERED", "TP1_HIT", "TP2_HIT", "STOPPED_OUT", "PENDING", "CANCELLED", "EXPIRED"
    val statusSummary: String = "",
    val detailedReasoning: String = "",
    val ema50: Double = 0.0,
    val ema200: Double = 0.0,
    val rsi14: Double = 50.0,
    val keyZoneLabel: String = "",
    val timestamp: Long = System.currentTimeMillis(),
    val expiryTimestamp: Long? = null,
    val isOfflineAvailable: Boolean = true
) {
    companion object {
        /**
         * Creates a TradeSignalEntity from a domain TradeSetup.
         */
        fun fromTradeSetup(
            setup: TradeSetup,
            signalType: String = "AI_CONFLUENCE",
            confidenceScore: Double = 0.85,
            expiryDurationMillis: Long = 4 * 3600 * 1000L // 4 hours default expiry
        ): TradeSignalEntity = TradeSignalEntity(
            signalId = UUID.randomUUID().toString(),
            pairSymbol = setup.pairSymbol,
            timeframe = setup.timeframe.label,
            action = setup.action.name,
            isValid = setup.isValid,
            entryPrice = setup.entryPrice,
            stopLoss = setup.stopLoss,
            takeProfit1 = setup.takeProfit1,
            takeProfit2 = setup.takeProfit2,
            riskRewardRatio = setup.riskRewardRatio,
            confidenceScore = confidenceScore,
            signalType = signalType,
            status = if (setup.isValid && setup.action != TradeAction.WAIT) "ACTIVE" else "PENDING",
            statusSummary = setup.statusSummary,
            detailedReasoning = setup.detailedReasoning,
            ema50 = setup.ema50,
            ema200 = setup.ema200,
            rsi14 = setup.rsi14,
            keyZoneLabel = setup.keyZoneLabel,
            timestamp = setup.timestamp,
            expiryTimestamp = setup.timestamp + expiryDurationMillis,
            isOfflineAvailable = true
        )
    }
}
