package com.example.analysis

import com.example.data.SavedSetupEntity

object HistoricalAiDataSeeder {

    fun generateHistoricalRecommendations(): List<SavedSetupEntity> {
        val now = System.currentTimeMillis()
        val oneDayMs = 86_400_000L

        return listOf(
            SavedSetupEntity(
                pairSymbol = "EUR/USD",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 1.08200,
                stopLoss = 1.07950,
                takeProfit1 = 1.08700,
                takeProfit2 = 1.09200,
                riskRewardRatio = 2.0,
                ema50 = 1.08150,
                ema200 = 1.07800,
                rsi14 = 34.2,
                keyZoneLabel = "H1 Demand Zone + 50 EMA Retest",
                status = "WON_TP1",
                notes = "AI Confluence: 50 EMA > 200 EMA uptrend, RSI-14 oversold bounce at 34.2. Target reached.",
                timestamp = now - (28 * oneDayMs),
                isAutoExecuted = true,
                lots = 0.40,
                currentPnl = 200.00,
                exitPrice = 1.08700,
                closedTimestamp = now - (28 * oneDayMs) + 14_400_000L
            ),
            SavedSetupEntity(
                pairSymbol = "US30",
                timeframe = "H4",
                action = "SELL",
                entryPrice = 39850.0,
                stopLoss = 40000.0,
                takeProfit1 = 39550.0,
                takeProfit2 = 39370.0,
                riskRewardRatio = 3.2,
                ema50 = 39900.0,
                ema200 = 40150.0,
                rsi14 = 71.8,
                keyZoneLabel = "4H Supply Block + Resistance Reject",
                status = "WON_TP2",
                notes = "AI Confluence: Double top at 40,000 psychological resistance, RSI overbought rejection.",
                timestamp = now - (26 * oneDayMs),
                isAutoExecuted = true,
                lots = 0.67,
                currentPnl = 321.60,
                exitPrice = 39370.0,
                closedTimestamp = now - (25 * oneDayMs)
            ),
            SavedSetupEntity(
                pairSymbol = "GBP/USD",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 1.29100,
                stopLoss = 1.28850,
                takeProfit1 = 1.29600,
                takeProfit2 = 1.30000,
                riskRewardRatio = 2.0,
                ema50 = 1.29050,
                ema200 = 1.28700,
                rsi14 = 44.5,
                keyZoneLabel = "Support Retest Zone",
                status = "STOPPED_OUT",
                notes = "AI Setup: News volatility triggered false breakout below 1.28850 support. Strict 1% risk limit.",
                timestamp = now - (25 * oneDayMs),
                isAutoExecuted = false,
                lots = 0.40,
                currentPnl = -100.00,
                exitPrice = 1.28840,
                closedTimestamp = now - (25 * oneDayMs) + 7_200_000L
            ),
            SavedSetupEntity(
                pairSymbol = "NAS100",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 19420.0,
                stopLoss = 19350.0,
                takeProfit1 = 19560.0,
                takeProfit2 = 19680.0,
                riskRewardRatio = 2.7,
                ema50 = 19410.0,
                ema200 = 19280.0,
                rsi14 = 38.0,
                keyZoneLabel = "Bullish Order Block + Gap Fill",
                status = "WON_TP2",
                notes = "AI Confluence: Fair value gap retest during NY open. Bullish engulfing candle.",
                timestamp = now - (23 * oneDayMs),
                isAutoExecuted = true,
                lots = 1.42,
                currentPnl = 369.20,
                exitPrice = 19680.0,
                closedTimestamp = now - (22 * oneDayMs)
            ),
            SavedSetupEntity(
                pairSymbol = "EUR/USD",
                timeframe = "M15",
                action = "SELL",
                entryPrice = 1.09150,
                stopLoss = 1.09350,
                takeProfit1 = 1.08750,
                takeProfit2 = 1.08500,
                riskRewardRatio = 2.0,
                ema50 = 1.09200,
                ema200 = 1.09450,
                rsi14 = 66.4,
                keyZoneLabel = "M15 Liquidity Sweep at High",
                status = "WON_TP1",
                notes = "AI Confluence: London high swept, immediate displacement lower.",
                timestamp = now - (21 * oneDayMs),
                isAutoExecuted = true,
                lots = 0.50,
                currentPnl = 200.00,
                exitPrice = 1.08750,
                closedTimestamp = now - (21 * oneDayMs) + 10_800_000L
            ),
            SavedSetupEntity(
                pairSymbol = "USD/JPY",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 151.200,
                stopLoss = 150.800,
                takeProfit1 = 152.000,
                takeProfit2 = 152.600,
                riskRewardRatio = 2.0,
                ema50 = 151.100,
                ema200 = 150.400,
                rsi14 = 42.1,
                keyZoneLabel = "50 EMA Dynamic Support",
                status = "WON_TP1",
                notes = "AI Confluence: Pullback to rising 50 EMA, bullish pin bar confirmation.",
                timestamp = now - (20 * oneDayMs),
                isAutoExecuted = false,
                lots = 0.25,
                currentPnl = 200.00,
                exitPrice = 152.000,
                closedTimestamp = now - (19 * oneDayMs)
            ),
            SavedSetupEntity(
                pairSymbol = "US30",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 40150.0,
                stopLoss = 40050.0,
                takeProfit1 = 40350.0,
                takeProfit2 = 40500.0,
                riskRewardRatio = 2.0,
                ema50 = 40120.0,
                ema200 = 39800.0,
                rsi14 = 48.0,
                keyZoneLabel = "Key S/R Flip Zone",
                status = "STOPPED_OUT",
                notes = "AI Setup: Powell speech flash whipsaw triggered 100 pt stop before reversal.",
                timestamp = now - (18 * oneDayMs),
                isAutoExecuted = true,
                lots = 1.00,
                currentPnl = -100.00,
                exitPrice = 40040.0,
                closedTimestamp = now - (18 * oneDayMs) + 3_600_000L
            ),
            SavedSetupEntity(
                pairSymbol = "GBP/USD",
                timeframe = "H4",
                action = "SELL",
                entryPrice = 1.30400,
                stopLoss = 1.30750,
                takeProfit1 = 1.29700,
                takeProfit2 = 1.29100,
                riskRewardRatio = 2.0,
                ema50 = 1.30500,
                ema200 = 1.31200,
                rsi14 = 68.2,
                keyZoneLabel = "Daily Key Resistance",
                status = "WON_TP1",
                notes = "AI Confluence: Rejection at major swing high, RSI bearish divergence.",
                timestamp = now - (17 * oneDayMs),
                isAutoExecuted = true,
                lots = 0.28,
                currentPnl = 196.00,
                exitPrice = 1.29700,
                closedTimestamp = now - (16 * oneDayMs)
            ),
            SavedSetupEntity(
                pairSymbol = "EUR/USD",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 1.08500,
                stopLoss = 1.08250,
                takeProfit1 = 1.09000,
                takeProfit2 = 1.09400,
                riskRewardRatio = 2.0,
                ema50 = 1.08450,
                ema200 = 1.08100,
                rsi14 = 36.8,
                keyZoneLabel = "Bullish Order Block + S/R Flip",
                status = "WON_TP2",
                notes = "AI Confluence: Clean 1:2 R:R followed by momentum continuation to TP2.",
                timestamp = now - (15 * oneDayMs),
                isAutoExecuted = false,
                lots = 0.40,
                currentPnl = 360.00,
                exitPrice = 1.09400,
                closedTimestamp = now - (14 * oneDayMs)
            ),
            SavedSetupEntity(
                pairSymbol = "NAS100",
                timeframe = "M15",
                action = "SELL",
                entryPrice = 19780.0,
                stopLoss = 19850.0,
                takeProfit1 = 19640.0,
                takeProfit2 = 19520.0,
                riskRewardRatio = 2.0,
                ema50 = 19800.0,
                ema200 = 19920.0,
                rsi14 = 72.0,
                keyZoneLabel = "Overextended Retest + 50 EMA",
                status = "WON_TP1",
                notes = "AI Confluence: Overbought pullback, clean rejection of falling 50 EMA.",
                timestamp = now - (14 * oneDayMs),
                isAutoExecuted = true,
                lots = 1.42,
                currentPnl = 198.80,
                exitPrice = 19640.0,
                closedTimestamp = now - (13 * oneDayMs)
            ),
            SavedSetupEntity(
                pairSymbol = "US30",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 40380.0,
                stopLoss = 40260.0,
                takeProfit1 = 40620.0,
                takeProfit2 = 40800.0,
                riskRewardRatio = 2.0,
                ema50 = 40350.0,
                ema200 = 40050.0,
                rsi14 = 41.5,
                keyZoneLabel = "Rising Trendline Confluence",
                status = "WON_TP2",
                notes = "AI Confluence: Confluence of 50 EMA and trendline support. Runner hit TP2.",
                timestamp = now - (12 * oneDayMs),
                isAutoExecuted = true,
                lots = 0.83,
                currentPnl = 348.60,
                exitPrice = 40800.0,
                closedTimestamp = now - (11 * oneDayMs)
            ),
            SavedSetupEntity(
                pairSymbol = "USD/JPY",
                timeframe = "H1",
                action = "SELL",
                entryPrice = 153.600,
                stopLoss = 154.000,
                takeProfit1 = 152.800,
                takeProfit2 = 152.200,
                riskRewardRatio = 2.0,
                ema50 = 153.700,
                ema200 = 154.300,
                rsi14 = 63.0,
                keyZoneLabel = "Resistance Zone Retest",
                status = "STOPPED_OUT",
                notes = "AI Setup: BoJ unexpected comment caused rapid yen sell-off, hitting 40 pip SL.",
                timestamp = now - (10 * oneDayMs),
                isAutoExecuted = false,
                lots = 0.25,
                currentPnl = -100.00,
                exitPrice = 154.050,
                closedTimestamp = now - (10 * oneDayMs) + 5_400_000L
            ),
            SavedSetupEntity(
                pairSymbol = "GBP/USD",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 1.30800,
                stopLoss = 1.30500,
                takeProfit1 = 1.31400,
                takeProfit2 = 1.31800,
                riskRewardRatio = 2.0,
                ema50 = 1.30750,
                ema200 = 1.30200,
                rsi14 = 39.2,
                keyZoneLabel = "H1 Demand Zone + EMA 50",
                status = "WON_TP1",
                notes = "AI Confluence: London breakout pullback, RSI oversold recovery.",
                timestamp = now - (9 * oneDayMs),
                isAutoExecuted = true,
                lots = 0.33,
                currentPnl = 198.00,
                exitPrice = 1.31400,
                closedTimestamp = now - (8 * oneDayMs)
            ),
            SavedSetupEntity(
                pairSymbol = "EUR/USD",
                timeframe = "H1",
                action = "SELL",
                entryPrice = 1.09450,
                stopLoss = 1.09700,
                takeProfit1 = 1.08950,
                takeProfit2 = 1.08600,
                riskRewardRatio = 2.0,
                ema50 = 1.09500,
                ema200 = 1.09900,
                rsi14 = 69.5,
                keyZoneLabel = "H1 Supply Block + Resistance",
                status = "WON_TP1",
                notes = "AI Confluence: Rejection of 1.0950 key level with RSI overbought reversal.",
                timestamp = now - (7 * oneDayMs),
                isAutoExecuted = true,
                lots = 0.40,
                currentPnl = 200.00,
                exitPrice = 1.08950,
                closedTimestamp = now - (7 * oneDayMs) + 18_000_000L
            ),
            SavedSetupEntity(
                pairSymbol = "US30",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 40750.0,
                stopLoss = 40600.0,
                takeProfit1 = 41050.0,
                takeProfit2 = 41300.0,
                riskRewardRatio = 2.0,
                ema50 = 40700.0,
                ema200 = 40250.0,
                rsi14 = 43.0,
                keyZoneLabel = "Daily Support + Liquidity Sweep",
                status = "WON_TP2",
                notes = "AI Confluence: Institutional buying at round number 40,700. Reached TP2.",
                timestamp = now - (6 * oneDayMs),
                isAutoExecuted = true,
                lots = 0.67,
                currentPnl = 368.50,
                exitPrice = 41300.0,
                closedTimestamp = now - (5 * oneDayMs)
            ),
            SavedSetupEntity(
                pairSymbol = "NAS100",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 19950.0,
                stopLoss = 19880.0,
                takeProfit1 = 20090.0,
                takeProfit2 = 20220.0,
                riskRewardRatio = 2.0,
                ema50 = 19920.0,
                ema200 = 19700.0,
                rsi14 = 37.4,
                keyZoneLabel = "Order Block + 50 EMA Retest",
                status = "WON_TP1",
                notes = "AI Confluence: Dip to 50 EMA bought aggressively by tech buyers.",
                timestamp = now - (4 * oneDayMs),
                isAutoExecuted = false,
                lots = 1.42,
                currentPnl = 198.80,
                exitPrice = 20090.0,
                closedTimestamp = now - (4 * oneDayMs) + 9_000_000L
            ),
            SavedSetupEntity(
                pairSymbol = "USD/JPY",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 152.100,
                stopLoss = 151.700,
                takeProfit1 = 152.900,
                takeProfit2 = 153.500,
                riskRewardRatio = 2.0,
                ema50 = 152.000,
                ema200 = 151.200,
                rsi14 = 41.0,
                keyZoneLabel = "Support Retest Confluence",
                status = "STOPPED_OUT",
                notes = "AI Setup: Market stalled in tight range, stop clipped by 3 pips before rally.",
                timestamp = now - (3 * oneDayMs),
                isAutoExecuted = true,
                lots = 0.25,
                currentPnl = -100.00,
                exitPrice = 151.680,
                closedTimestamp = now - (3 * oneDayMs) + 6_000_000L
            ),
            SavedSetupEntity(
                pairSymbol = "GBP/USD",
                timeframe = "H1",
                action = "SELL",
                entryPrice = 1.31900,
                stopLoss = 1.32200,
                takeProfit1 = 1.31300,
                takeProfit2 = 1.30800,
                riskRewardRatio = 2.0,
                ema50 = 1.32000,
                ema200 = 1.32500,
                rsi14 = 70.5,
                keyZoneLabel = "4H S/R Barrier Rejection",
                status = "WON_TP1",
                notes = "AI Confluence: 1.3200 psychological barrier held firmly, RSI overbought.",
                timestamp = now - (2 * oneDayMs),
                isAutoExecuted = true,
                lots = 0.33,
                currentPnl = 198.00,
                exitPrice = 1.31300,
                closedTimestamp = now - (2 * oneDayMs) + 12_000_000L
            ),
            SavedSetupEntity(
                pairSymbol = "EUR/USD",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 1.08700,
                stopLoss = 1.08450,
                takeProfit1 = 1.09200,
                takeProfit2 = 1.09550,
                riskRewardRatio = 2.0,
                ema50 = 1.08650,
                ema200 = 1.08300,
                rsi14 = 35.6,
                keyZoneLabel = "H1 Key Demand + RSI Oversold",
                status = "WON_TP1",
                notes = "AI Confluence: All 4 discipline rules confirmed. Reached 1:2 R:R target.",
                timestamp = now - (1 * oneDayMs),
                isAutoExecuted = true,
                lots = 0.40,
                currentPnl = 200.00,
                exitPrice = 1.09200,
                closedTimestamp = now - (1 * oneDayMs) + 8_000_000L
            ),
            SavedSetupEntity(
                pairSymbol = "US30",
                timeframe = "H1",
                action = "BUY",
                entryPrice = 41150.0,
                stopLoss = 41000.0,
                takeProfit1 = 41450.0,
                takeProfit2 = 41700.0,
                riskRewardRatio = 2.0,
                ema50 = 41100.0,
                ema200 = 40600.0,
                rsi14 = 44.0,
                keyZoneLabel = "Breakout Retest + Institutional Order Block",
                status = "ACTIVE",
                notes = "⚡ Live Trade running: 50 EMA > 200 EMA uptrend, RSI neutral 44.0, targeting 41,450.",
                timestamp = now - (4 * 3600_000L),
                isAutoExecuted = true,
                lots = 0.67,
                currentPnl = 134.00,
                exitPrice = 0.0,
                closedTimestamp = null
            )
        )
    }
}
